# Generated by Django 4.2.27 on 2024-11-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_image_url_product_image'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='product',
        #     name='variants',
        #     field=models.JSONField(blank=True, default=list),
        # ),
    ]
