# Generated by Django 4.2.27 on 2026-02-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
