# Generated by Antigravity

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_display_order'),
    ]

    operations = [
       # No operation needed as fields exist, but we must update state
       # actually we just need code to match db, we dont deploy migrations
       # but we need to update serializers to allow writing to it.
    ]
