# Generated by Django 4.2.27 on 2026-02-06 05:49

from django.db import migrations, models



def add_columns_if_not_exists(apps, schema_editor):
    try:
        Product = apps.get_model('api', 'Product')
        db_table = Product._meta.db_table
    except LookupError:
        # Fallback if model not found, though unlikely
        return

    # Check if fields exist
    with schema_editor.connection.cursor() as cursor:
        columns = [c.name for c in schema_editor.connection.introspection.get_table_description(cursor, db_table)]
    
    new_fields = ['cogs', 'marketing_cost', 'shipping_cost']
    
    for name in new_fields:
        if name not in columns:
            print(f"Adding column {name} to {db_table}...")
            # Using raw SQL for safety and simplicity across backends knowing the type is simple decimal
            sql_type = "numeric(10, 2)"
            # For SQLite, it handles numeric affinity.
            
            # Construct SQL
            sql = f"ALTER TABLE {schema_editor.quote_name(db_table)} ADD COLUMN {schema_editor.quote_name(name)} {sql_type} NULL DEFAULT 0.0"
            schema_editor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sync_state'),
    ]


    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='cogs',
                    field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
                ),
                migrations.AddField(
                    model_name='product',
                    name='marketing_cost',
                    field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
                ),
                migrations.AddField(
                    model_name='product',
                    name='shipping_cost',
                    field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_columns_if_not_exists),
            ],
        ),
    ]

